## 101 `numpy` excersises by: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

### 1. Import numpy as np and see the version


In [2]:
import numpy as np 
np.__version__

'1.17.2'

### 2. How to create a 1D array?

In [20]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array = np.asarray(range(10))
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?

In [23]:
array = np.ones([3,3]).astype(bool)
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
array = np.ones([3,3],dtype = bool)
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?

In [26]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[np.where((arr%2==1))]

array([1, 3, 5, 7, 9])

In [29]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?

In [34]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[arr%2==1]= -1

### 6. How to replace items that satisfy a condition without affecting the original array?

In [68]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
out = arr.copy()
out[out%2==1]= -1

In [46]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

or

In [70]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)

In [71]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 7. How to reshape an array?

In [74]:
arr = np.arange(10)
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Observation: Setting to -1 automatically decides the number of cols

In [75]:
arr = np.arange(10)
arr = arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?

In [76]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [79]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [80]:
np.concatenate([a,b],axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?


In [76]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [81]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [82]:
np.concatenate([a,b],axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?

In [83]:
a = np.array([1,2,3])

In [100]:
np.concatenate([a.repeat(repeats = 3),np.tile(a,2)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?

In [101]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [102]:
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?

In [116]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
b = set(b)
a = a.tolist()
a = np.array([x for x in a if x not in b])

In [126]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a[~np.isin(a,b)]

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?

In [127]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [149]:
np.where([a==b][0])

(array([1, 3, 5, 7]),)

### 14. How to extract all numbers between a given range from a numpy array?

In [150]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [153]:
a[(a>5)&(a<=10)]

array([ 6,  9, 10])

In [155]:
a[np.where((a>5)&(a<=10))]

array([ 6,  9, 10])

### 15. How to extract all numbers between a given range from a numpy array?

In [6]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


In [7]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [8]:
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?

In [51]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
c1 =arr[:,0].copy()
arr[:,0] = arr[:,1]
arr[:,1] = c1
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [53]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 18. How to reverse the rows of a 2D array?


In [64]:
arr = np.arange(9).reshape(3,-1)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
arr[list(reversed(list(range(3)))),:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 19. How to reverse the rows of a 2D array?


In [70]:
arr[:,list(reversed(list(range(3))))]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to create a 2D array containing random floats between 5 and 10?

In [79]:
random = np.random.random_sample([5,5])

In [84]:
random = random*5+5
random

array([[49.86890508, 40.07964094, 47.98118064, 48.16491871, 47.24219723],
       [40.22361871, 45.4285462 , 40.70334573, 51.89730885, 37.80419234],
       [32.80254866, 32.2864311 , 39.27272051, 51.01597791, 41.94542189],
       [48.77320695, 46.49948622, 34.61835962, 38.95867741, 46.37150029],
       [32.70700141, 53.45686634, 52.67135561, 43.496171  , 44.717429  ]])

In [83]:
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[7.57093256, 6.12220059, 6.01007581],
       [5.43278917, 8.09672098, 9.71908204],
       [9.42783293, 6.86575861, 6.58561509],
       [9.95675798, 5.38985784, 7.13378245],
       [5.43806679, 8.33571121, 7.76099028]])

### 21. How to print only 3 decimal places in python numpy array?

In [86]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.76841087, 0.38718208, 0.57392372],
       [0.70390851, 0.16114898, 0.89472755],
       [0.58510846, 0.9170157 , 0.95216348],
       [0.56620316, 0.63314063, 0.07929399],
       [0.76685867, 0.93716561, 0.38258943]])

In [88]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
rand_arr

array([[0.768, 0.387, 0.574],
       [0.704, 0.161, 0.895],
       [0.585, 0.917, 0.952],
       [0.566, 0.633, 0.079],
       [0.767, 0.937, 0.383]])

### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [93]:
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])